// Dữ liệu mẫu được trích xuất từ dữ liệu thực tế dự án n8n_LS
window.DEMO_RULES = [
  {
    "category": "TOPS",
    "description": "Áo 1 món: tee, top, polo, shirt, hoodie/hoody, sweatshirt. Romper 1 món và bodysuit 1 món (1pc) cũng thuộc TOPS. Mô tả có \"+ ATTACHMENT\" vẫn xếp theo món chính.\nVD: S/S TEE, L/S KNIT TOP, DRI-FIT L/S TOP, FULL ZIP HOODY, PULL-OVER HOODY, ROMPER, BABY KNIT ROMPER, ROMPER + ATTACHMENT, SS TEE+ATTACHMENT"
  },
  {
    "category": "BOTTOMS",
    "description": "Quần, short, váy 1 món: pant, short, legging, jogger, skirt, skort; boys swimsuits/boardshorts.\nVD: FLEECE PANT, FRENCH TERRY PANT, FLEECE SHORT, WOVEN SHORT, KNIT LEGGING"
  },
  {
    "category": "COVERALLS",
    "description": "Coverall, footed coverall; bodysuit/romper nhiều cái trong một gói (multi-pack, 2PK, 3pc creepers).\nVD: COVERALL, FOOTED COVERALL, 2PK FOOTED COVERALL, 2PK ROMPER"
  },
  {
    "category": "SETS",
    "description": "Bộ nhiều món: track set, short set, pant set, tricot set, 2PC/3PC set. Mô tả kết thúc bằng SET luôn xếp SETS, kể cả khi phía trước có pant, short, bodysuit hay dress. Nhiều món nối bằng dấu \"+\" cũng là SETS (trừ phần ATTACHMENT).\nVD: KNIT SHORT SET, FLEECE PANT SET, 3PC PANT SET, BODYSUIT PANT SET, 2PC DRESS SET, TRICOT SET, BODYSUIT+PANT+ATTACHMENT"
  },
  {
    "category": "OUTERWEAR",
    "description": "Áo khoác: jacket, coat, vest, outerwear.\nVD: LIGHT WEIGHT OUTERWEAR"
  },
  {
    "category": "BOX SETS",
    "description": "Set đóng hộp (bộ quà tặng đóng sẵn trong hộp)."
  },
  {
    "category": "HOSIERY",
    "description": "Tất/vớ: socks, crew, quarter, no show, ankle (thường đóng gói 6PK, 8PK); bib, blanket.\nVD: 6PK CREW SOCK, 6PK QUARTER SOCK, 6PK NO SHOW SOCK, 8PK CREW SOCK"
  },
  {
    "category": "UNDERWEAR",
    "description": "Đồ lót: underwear, brief, boxer, undershirt.\nVD: UNDERSHIRT"
  },
  {
    "category": "COLD WEATHER",
    "description": "Beanie, hat, cap, gloves, mittens, scarf. Tên sheet trong SOF đúng là \"COLD WEATHER\"."
  },
  {
    "category": "BAGS",
    "description": "Túi, balo: bag, backpack."
  },
  {
    "category": "ACCESSORIES",
    "description": "Phụ kiện: backpack, lunch tote, sling, crossbody, duffle, shoe strings. Chỉ có trong SOF K413M; với account này túi và balo nằm ở đây thay vì BAGS."
  },
  {
    "category": "GIRLS SWIMWEAR",
    "description": "Đồ bơi bé gái (SOF H040M)."
  },
  {
    "category": "1 PC SWIMWEAR",
    "description": "Đồ bơi 1 mảnh (SOF K816M, N748M)."
  },
  {
    "category": "2-3 PC SWIMWEAR",
    "description": "Đồ bơi 2–3 mảnh (SOF K816M, N748M)."
  },
  {
    "category": "SWEATER-YARN",
    "description": "Áo len, sweater dệt sợi (SOF H040M)."
  },
  {
    "category": "HUGGIES",
    "description": "Hàng thương hiệu Huggies (SOF H040M)."
  },
  {
    "category": "LACOSTE TOYS",
    "description": "Đồ chơi Lacoste (SOF H040M)."
  },
  {
    "category": "DRESS (chưa có sheet)",
    "description": "Dress, dress + attachment. Các SOF hiện tại chưa có sheet riêng cho váy liền — cần xác nhận với khách trước khi xử lý.\nVD: DRESS, DRESS + ATTACHMENT"
  }
];
window.DEMO_SUMMARY = {
  "input_file": "VLK VLH LPO 09.09.26.XLS",
  "sof_file": "H040M Stock Replenishment SO Form 8.31.26.xlsx",
  "rule_file": "Rule_cho_Hanger.docx",
  "total_order_rows": 5817,
  "matched": 1898,
  "review": 2561,
  "mismatch": 32,
  "skipped_existing_hanger_data": 0
};
window.DEMO_ROWS = [
  {
    "row_number": 222,
    "po_number": "0751361",
    "account": "H040M",
    "division": "G",
    "label": "WH",
    "label_name": "WITH HANGER",
    "ref_number": "NKG-KPN743",
    "style": "06N743",
    "product_description": "BODYSUIT PANT SET",
    "product_category": "SETS",
    "size_configuration": "NB0-3 - NB 3M - NB 6M - NB 9M",
    "order_hang_flat": "Hang",
    "sof_hang_flat": "Hang",
    "hanger_code": "495/9508",
    "hanger_color": "WHITE",
    "color_sizer": "White size clip / black lettering",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "SETS",
    "source_cells": "A26:C26,A31:C31,B37:B37",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.8,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "NKG-KPN743",
      "Style": "06N743",
      "Product Description": "BODYSUIT PANT SET",
      "Color": "AAH",
      "Label": "WH",
      "Label Name": "WITH HANGER",
      "Account": "H040M",
      "PO#": "0751361",
      "PO Qty": "690",
      "Size Configuration": "NB0-3 - NB 3M - NB 6M - NB 9M",
      "Pack Ratio": "1 - 2 - 2 - 1",
      "Master Box Quantity": "6",
      "Hang/Flat": "Hang",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 224,
    "po_number": "0766509",
    "account": "H040M",
    "division": "G",
    "label": "WH",
    "label_name": "WITH HANGER",
    "ref_number": "NKG-KPN743",
    "style": "06N743",
    "product_description": "BODYSUIT PANT SET",
    "product_category": "SETS",
    "size_configuration": "NB0-3 - NB 3M - NB 6M - NB 9M",
    "order_hang_flat": "Hang",
    "sof_hang_flat": "Hang",
    "hanger_code": "495/9508",
    "hanger_color": "WHITE",
    "color_sizer": "White size clip / black lettering",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "SETS",
    "source_cells": "A26:C26,A31:C31,B37:B37",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.8,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "NKG-KPN743",
      "Style": "06N743",
      "Product Description": "BODYSUIT PANT SET",
      "Color": "BGZ",
      "Label": "WH",
      "Label Name": "WITH HANGER",
      "Account": "H040M",
      "PO#": "0766509",
      "PO Qty": "438",
      "Size Configuration": "NB0-3 - NB 3M - NB 6M - NB 9M",
      "Pack Ratio": "1 - 2 - 2 - 1",
      "Master Box Quantity": "6",
      "Hang/Flat": "Hang",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 227,
    "po_number": "0751363",
    "account": "H040M",
    "division": "G",
    "label": "WH",
    "label_name": "WITH HANGER",
    "ref_number": "NKG-KPN743",
    "style": "06N743",
    "product_description": "BODYSUIT PANT SET",
    "product_category": "SETS",
    "size_configuration": "NB0-3 - NB 3M - NB 6M - NB 9M",
    "order_hang_flat": "Hang",
    "sof_hang_flat": "Hang",
    "hanger_code": "495/9508",
    "hanger_color": "WHITE",
    "color_sizer": "White size clip / black lettering",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "SETS",
    "source_cells": "A26:C26,A31:C31,B37:B37",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.8,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "NKG-KPN743",
      "Style": "06N743",
      "Product Description": "BODYSUIT PANT SET",
      "Color": "P6I",
      "Label": "WH",
      "Label Name": "WITH HANGER",
      "Account": "H040M",
      "PO#": "0751363",
      "PO Qty": "1434",
      "Size Configuration": "NB0-3 - NB 3M - NB 6M - NB 9M",
      "Pack Ratio": "1 - 2 - 2 - 1",
      "Master Box Quantity": "6",
      "Hang/Flat": "Hang",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 266,
    "po_number": "0769719",
    "account": "H040M",
    "division": "G",
    "label": "-V",
    "label_name": "ST HANG ALT PACK",
    "ref_number": "NKG-KSK809",
    "style": "16K809",
    "product_description": "KNIT SHORT SET",
    "product_category": "SETS",
    "size_configuration": "12M - 18M - 24M",
    "order_hang_flat": "Hang",
    "sof_hang_flat": "Hang",
    "hanger_code": "496/9508",
    "hanger_color": "WHITE",
    "color_sizer": "White size clip / black lettering",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "SETS",
    "source_cells": "B25:E25,B31:C31,B37:B37",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.8,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "NKG-KSK809",
      "Style": "16K809",
      "Product Description": "KNIT SHORT SET",
      "Color": "AAJ",
      "Label": "-V",
      "Label Name": "ST HANG ALT PACK",
      "Account": "H040M",
      "PO#": "0769719",
      "PO Qty": "3000",
      "Size Configuration": "12M - 18M - 24M",
      "Pack Ratio": "4 - 4 - 4",
      "Master Box Quantity": "12",
      "Hang/Flat": "Hang",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 267,
    "po_number": "0769720",
    "account": "H040M",
    "division": "G",
    "label": "-V",
    "label_name": "ST HANG ALT PACK",
    "ref_number": "NKG-KSK809",
    "style": "16K809",
    "product_description": "KNIT SHORT SET",
    "product_category": "SETS",
    "size_configuration": "12M - 18M - 24M",
    "order_hang_flat": "Hang",
    "sof_hang_flat": "Hang",
    "hanger_code": "496/9508",
    "hanger_color": "WHITE",
    "color_sizer": "White size clip / black lettering",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "SETS",
    "source_cells": "B25:E25,B31:C31,B37:B37",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.8,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "NKG-KSK809",
      "Style": "16K809",
      "Product Description": "KNIT SHORT SET",
      "Color": "AFN",
      "Label": "-V",
      "Label Name": "ST HANG ALT PACK",
      "Account": "H040M",
      "PO#": "0769720",
      "PO Qty": "3000",
      "Size Configuration": "12M - 18M - 24M",
      "Pack Ratio": "4 - 4 - 4",
      "Master Box Quantity": "12",
      "Hang/Flat": "Hang",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 268,
    "po_number": "0769721",
    "account": "H040M",
    "division": "G",
    "label": "-V",
    "label_name": "ST HANG ALT PACK",
    "ref_number": "NKG-KSK809",
    "style": "16K809",
    "product_description": "KNIT SHORT SET",
    "product_category": "SETS",
    "size_configuration": "12M - 18M - 24M",
    "order_hang_flat": "Hang",
    "sof_hang_flat": "Hang",
    "hanger_code": "496/9508",
    "hanger_color": "WHITE",
    "color_sizer": "White size clip / black lettering",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "SETS",
    "source_cells": "B25:E25,B31:C31,B37:B37",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.8,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "NKG-KSK809",
      "Style": "16K809",
      "Product Description": "KNIT SHORT SET",
      "Color": "BA2",
      "Label": "-V",
      "Label Name": "ST HANG ALT PACK",
      "Account": "H040M",
      "PO#": "0769721",
      "PO Qty": "3000",
      "Size Configuration": "12M - 18M - 24M",
      "Pack Ratio": "4 - 4 - 4",
      "Master Box Quantity": "12",
      "Hang/Flat": "Hang",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 269,
    "po_number": "0769722",
    "account": "H040M",
    "division": "G",
    "label": "-V",
    "label_name": "ST HANG ALT PACK",
    "ref_number": "NKG-KSK809",
    "style": "16K809",
    "product_description": "KNIT SHORT SET",
    "product_category": "SETS",
    "size_configuration": "12M - 18M - 24M",
    "order_hang_flat": "Hang",
    "sof_hang_flat": "Hang",
    "hanger_code": "496/9508",
    "hanger_color": "WHITE",
    "color_sizer": "White size clip / black lettering",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "SETS",
    "source_cells": "B25:E25,B31:C31,B37:B37",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.8,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "NKG-KSK809",
      "Style": "16K809",
      "Product Description": "KNIT SHORT SET",
      "Color": "P6I",
      "Label": "-V",
      "Label Name": "ST HANG ALT PACK",
      "Account": "H040M",
      "PO#": "0769722",
      "PO Qty": "3000",
      "Size Configuration": "12M - 18M - 24M",
      "Pack Ratio": "4 - 4 - 4",
      "Master Box Quantity": "12",
      "Hang/Flat": "Hang",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 270,
    "po_number": "0761515",
    "account": "H040M",
    "division": "G",
    "label": "-V",
    "label_name": "ST HANG ALT PACK",
    "ref_number": "NKG-KSN024",
    "style": "16N024",
    "product_description": "KNIT SHORT SET",
    "product_category": "SETS",
    "size_configuration": "12M - 18M - 24M",
    "order_hang_flat": "Hang",
    "sof_hang_flat": "Hang",
    "hanger_code": "496/9508",
    "hanger_color": "WHITE",
    "color_sizer": "White size clip / black lettering",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "SETS",
    "source_cells": "B25:E25,B31:C31,B37:B37",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.8,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "NKG-KSN024",
      "Style": "16N024",
      "Product Description": "KNIT SHORT SET",
      "Color": "AFN",
      "Label": "-V",
      "Label Name": "ST HANG ALT PACK",
      "Account": "H040M",
      "PO#": "0761515",
      "PO Qty": "15000",
      "Size Configuration": "12M - 18M - 24M",
      "Pack Ratio": "4 - 4 - 4",
      "Master Box Quantity": "12",
      "Hang/Flat": "Hang",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 3,
    "po_number": "0711997",
    "account": "H040M",
    "division": "G",
    "label": "79",
    "label_name": "HOSIERY 7-9",
    "ref_number": "JHB-6W0871",
    "style": "BJ0871",
    "product_description": "6PK CREW SOCK",
    "product_category": "HOSIERY",
    "size_configuration": "7-9",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "Flat",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "HOSIERY",
    "source_cells": "A3:B5",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.95,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "H",
      "Year": "2026",
      "Ref#": "JHB-6W0871",
      "Style": "BJ0871",
      "Product Description": "6PK CREW SOCK",
      "Color": "UUG",
      "Label": "79",
      "Label Name": "HOSIERY 7-9",
      "Account": "H040M",
      "PO#": "0711997",
      "PO Qty": "3000",
      "Size Configuration": "7-9",
      "Pack Ratio": "12",
      "Master Box Quantity": "12",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 4,
    "po_number": "0711998",
    "account": "H040M",
    "division": "G",
    "label": "91",
    "label_name": "HOSIERY 9-11",
    "ref_number": "JHB-6W0871",
    "style": "BJ0871",
    "product_description": "6PK CREW SOCK",
    "product_category": "HOSIERY",
    "size_configuration": "9-11",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "Flat",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "HOSIERY",
    "source_cells": "A3:B5",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.95,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "H",
      "Year": "2026",
      "Ref#": "JHB-6W0871",
      "Style": "BJ0871",
      "Product Description": "6PK CREW SOCK",
      "Color": "UUG",
      "Label": "91",
      "Label Name": "HOSIERY 9-11",
      "Account": "H040M",
      "PO#": "0711998",
      "PO Qty": "7008",
      "Size Configuration": "9-11",
      "Pack Ratio": "12",
      "Master Box Quantity": "12",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 5,
    "po_number": "0711999",
    "account": "H040M",
    "division": "G",
    "label": "79",
    "label_name": "HOSIERY 7-9",
    "ref_number": "JHB-6W0871",
    "style": "BJ0871",
    "product_description": "6PK CREW SOCK",
    "product_category": "HOSIERY",
    "size_configuration": "7-9",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "Flat",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "HOSIERY",
    "source_cells": "A3:B5",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.95,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "H",
      "Year": "2026",
      "Ref#": "JHB-6W0871",
      "Style": "BJ0871",
      "Product Description": "6PK CREW SOCK",
      "Color": "023",
      "Label": "79",
      "Label Name": "HOSIERY 7-9",
      "Account": "H040M",
      "PO#": "0711999",
      "PO Qty": "12000",
      "Size Configuration": "7-9",
      "Pack Ratio": "12",
      "Master Box Quantity": "12",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 6,
    "po_number": "0712000",
    "account": "H040M",
    "division": "G",
    "label": "91",
    "label_name": "HOSIERY 9-11",
    "ref_number": "JHB-6W0871",
    "style": "BJ0871",
    "product_description": "6PK CREW SOCK",
    "product_category": "HOSIERY",
    "size_configuration": "9-11",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "Flat",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "HOSIERY",
    "source_cells": "A3:B5",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.95,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "H",
      "Year": "2026",
      "Ref#": "JHB-6W0871",
      "Style": "BJ0871",
      "Product Description": "6PK CREW SOCK",
      "Color": "023",
      "Label": "91",
      "Label Name": "HOSIERY 9-11",
      "Account": "H040M",
      "PO#": "0712000",
      "PO Qty": "28008",
      "Size Configuration": "9-11",
      "Pack Ratio": "12",
      "Master Box Quantity": "12",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 7,
    "po_number": "0721587",
    "account": "H040M",
    "division": "G",
    "label": "79",
    "label_name": "HOSIERY 7-9",
    "ref_number": "JHG-6Q0858",
    "style": "GJ0858",
    "product_description": "6PK QUARTER SOCK",
    "product_category": "HOSIERY",
    "size_configuration": "7-9",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "Flat",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "HOSIERY",
    "source_cells": "A3:B5",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.95,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "H",
      "Year": "2026",
      "Ref#": "JHG-6Q0858",
      "Style": "GJ0858",
      "Product Description": "6PK QUARTER SOCK",
      "Color": "AFL",
      "Label": "79",
      "Label Name": "HOSIERY 7-9",
      "Account": "H040M",
      "PO#": "0721587",
      "PO Qty": "15000",
      "Size Configuration": "7-9",
      "Pack Ratio": "12",
      "Master Box Quantity": "12",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 8,
    "po_number": "0721589",
    "account": "H040M",
    "division": "G",
    "label": "91",
    "label_name": "HOSIERY 9-11",
    "ref_number": "JHG-6Q0858",
    "style": "GJ0858",
    "product_description": "6PK QUARTER SOCK",
    "product_category": "HOSIERY",
    "size_configuration": "9-11",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "Flat",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "HOSIERY",
    "source_cells": "A3:B5",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "LLM_DEEPSEEK_VERIFIED_SOURCE",
    "confidence": 0.95,
    "status": "MATCHED",
    "validation_note": "",
    "original_values": {
      "Division": "G",
      "Season": "H",
      "Year": "2026",
      "Ref#": "JHG-6Q0858",
      "Style": "GJ0858",
      "Product Description": "6PK QUARTER SOCK",
      "Color": "AFL",
      "Label": "91",
      "Label Name": "HOSIERY 9-11",
      "Account": "H040M",
      "PO#": "0721589",
      "PO Qty": "1332",
      "Size Configuration": "9-11",
      "Pack Ratio": "12",
      "Master Box Quantity": "12",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 40,
    "po_number": "0657755",
    "account": "H040M",
    "division": "G",
    "label": "WH",
    "label_name": "WITH HANGER",
    "ref_number": "JHM-US0869",
    "style": "JM0869",
    "product_description": "UNDERSHIRT",
    "product_category": "TOPS",
    "size_configuration": "S - M - L - XL",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "",
    "source_cells": "",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "",
    "confidence": 0,
    "status": "REVIEW",
    "validation_note": "No matching SOF rule after applying rule priorities; DeepSeek requested review: The WH / 'WITH HANGER' label points to the TOPS sheet's 'WH / YW hanger required' section, but the order's own hang/flat value is Flat, size 'S - M - L - XL' matches none of the TOPS size rows, and no hanger colour is stated on the sheet, so the governing rule cannot be fixed without guessing.",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "JHM-US0869",
      "Style": "JM0869",
      "Product Description": "UNDERSHIRT",
      "Color": "F00",
      "Label": "WH",
      "Label Name": "WITH HANGER",
      "Account": "H040M",
      "PO#": "0657755",
      "PO Qty": "648",
      "Size Configuration": "S - M - L - XL",
      "Pack Ratio": "1 - 3 - 3 - 1",
      "Master Box Quantity": "8",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 41,
    "po_number": "0646597",
    "account": "H040M",
    "division": "G",
    "label": "",
    "label_name": "",
    "ref_number": "JHM-US0869",
    "style": "JRX869",
    "product_description": "UNDERSHIRT",
    "product_category": "TOPS",
    "size_configuration": "XXL",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "",
    "source_cells": "",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "",
    "confidence": 0,
    "status": "REVIEW",
    "validation_note": "No matching SOF rule after applying rule priorities; DeepSeek confidence 0.7 is below required 0.8",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "JHM-US0869",
      "Style": "JRX869",
      "Product Description": "UNDERSHIRT",
      "Color": "F00",
      "Label": "",
      "Label Name": "",
      "Account": "H040M",
      "PO#": "0646597",
      "PO Qty": "312",
      "Size Configuration": "XXL",
      "Pack Ratio": "1",
      "Master Box Quantity": "24",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 42,
    "po_number": "0646598",
    "account": "H040M",
    "division": "G",
    "label": "",
    "label_name": "",
    "ref_number": "JHM-US0869",
    "style": "JRX869",
    "product_description": "UNDERSHIRT",
    "product_category": "TOPS",
    "size_configuration": "XXL",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "",
    "source_cells": "",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "",
    "confidence": 0,
    "status": "REVIEW",
    "validation_note": "No matching SOF rule after applying rule priorities; DeepSeek confidence 0.7 is below required 0.8",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "JHM-US0869",
      "Style": "JRX869",
      "Product Description": "UNDERSHIRT",
      "Color": "001",
      "Label": "",
      "Label Name": "",
      "Account": "H040M",
      "PO#": "0646598",
      "PO Qty": "312",
      "Size Configuration": "XXL",
      "Pack Ratio": "1",
      "Master Box Quantity": "24",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 43,
    "po_number": "0646599",
    "account": "H040M",
    "division": "G",
    "label": "",
    "label_name": "",
    "ref_number": "JHM-US0869",
    "style": "JRX869",
    "product_description": "UNDERSHIRT",
    "product_category": "TOPS",
    "size_configuration": "XXL",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "H040M  Stock Replenishment SO Form 8.31.26.xlsx",
    "source_sheet": "",
    "source_cells": "",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "",
    "confidence": 0,
    "status": "REVIEW",
    "validation_note": "No matching SOF rule after applying rule priorities; DeepSeek confidence 0.7 is below required 0.8",
    "original_values": {
      "Division": "G",
      "Season": "S",
      "Year": "2027",
      "Ref#": "JHM-US0869",
      "Style": "JRX869",
      "Product Description": "UNDERSHIRT",
      "Color": "023",
      "Label": "",
      "Label Name": "",
      "Account": "H040M",
      "PO#": "0646599",
      "PO Qty": "312",
      "Size Configuration": "XXL",
      "Pack Ratio": "1",
      "Master Box Quantity": "24",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 50,
    "po_number": "0720508",
    "account": "N748M",
    "division": "G",
    "label": "KB",
    "label_name": "NIKE.COM - ALTERNATE",
    "ref_number": "JHN-6Q0734",
    "style": "NJ0734",
    "product_description": "6PK QUARTER SOCK",
    "product_category": "HOSIERY",
    "size_configuration": "2-4",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "NIKE.COM SO Form N748M 5.27.26.xlsx",
    "source_sheet": "",
    "source_cells": "",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "",
    "confidence": 0,
    "status": "REVIEW",
    "validation_note": "No matching SOF rule after applying rule priorities; DeepSeek returned no decision",
    "original_values": {
      "Division": "G",
      "Season": "H",
      "Year": "2026",
      "Ref#": "JHN-6Q0734",
      "Style": "NJ0734",
      "Product Description": "6PK QUARTER SOCK",
      "Color": "A9Y",
      "Label": "KB",
      "Label Name": "NIKE.COM - ALTERNATE",
      "Account": "N748M",
      "PO#": "0720508",
      "PO Qty": "204",
      "Size Configuration": "2-4",
      "Pack Ratio": "12",
      "Master Box Quantity": "12",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  },
  {
    "row_number": 51,
    "po_number": "0720509",
    "account": "N748M",
    "division": "G",
    "label": "KE",
    "label_name": "NIKE.COM",
    "ref_number": "JHN-6Q0734",
    "style": "NJ0734",
    "product_description": "6PK QUARTER SOCK",
    "product_category": "HOSIERY",
    "size_configuration": "6-12",
    "order_hang_flat": "Flat",
    "sof_hang_flat": "",
    "hanger_code": "",
    "hanger_color": "",
    "color_sizer": "",
    "sticker_hanger": "",
    "size_sticker_hanger": "",
    "source_file": "NIKE.COM SO Form N748M 5.27.26.xlsx",
    "source_sheet": "",
    "source_cells": "",
    "source_section": "",
    "source_lines": "",
    "source_excerpt": "",
    "match_method": "",
    "confidence": 0,
    "status": "REVIEW",
    "validation_note": "No matching SOF rule after applying rule priorities; DeepSeek returned no decision",
    "original_values": {
      "Division": "G",
      "Season": "H",
      "Year": "2026",
      "Ref#": "JHN-6Q0734",
      "Style": "NJ0734",
      "Product Description": "6PK QUARTER SOCK",
      "Color": "A9Y",
      "Label": "KE",
      "Label Name": "NIKE.COM",
      "Account": "N748M",
      "PO#": "0720509",
      "PO Qty": "204",
      "Size Configuration": "6-12",
      "Pack Ratio": "12",
      "Master Box Quantity": "12",
      "Hang/Flat": "Flat",
      "Hanger code": "",
      "Hanger color": "",
      "Color Sizer": "",
      "Sticker hanger": "",
      "SIZE Sticker hanger": ""
    }
  }
];
